{
    'name': 'School Core',
    'version': '1.0',
    'category': 'Education',
    'sequence': 2,
    'summary': 'Core module for school management system',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'data/student_sequence.xml',
        'data/teacher_sequence.xml',
        'views/student_views.xml',
        'views/class_views.xml',
        'views/academic_views.xml',
        'views/subject_views.xml',
        'views/teacher_views.xml',
        'views/school_class_subject_view.xml',
        'views/section_views.xml',
        'views/exam_views.xml',
        'views/attendance_views.xml',
        'views/fee_views.xml',
        'views/parent_views.xml',
        'views/all_menus.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
